name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p build && chmod -R 0777 build
          make slides
      - name: Prepare Deploy
        run: |
          echo "# This branch is for deployment only" >> build/README.md
          mv build/slide-deck.html build/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          single-commit: true
          silent: true
